name: 'Linkinator'
author: 'Justin Beckwith'
description: 'A GitHub Action that checks your README and other markdown for 404s.'
branding:
  icon: 'link'
  color: 'purple'
inputs:
  paths:
    description: 'Paths to scan for 404s. Defaults to *.md.'
    default: '*.md'
    required: false
  concurrency:
    description: 'The number of connections to make simultaneously.'
    default: '100'
    required: false
  recurse:
    description: 'Recursively follow links on the same root domain.'
    default: 'false'
    required: false
  linksToSkip:
    description: 'List of urls in regexy form to not include in the check.'
    required: false
  skip:
    description: 'List of urls in regexy form to not include in the check.'
    required: false
  timeout:
    description: 'Request timeout in ms.  Defaults to 0 (no timeout).'
    default: '0'
    required: false
  markdown:
    description: 'Automatically parse and scan markdown if scanning from a location on disk.'
    default: 'true'
    required: false
  serverRoot:
    description: 'When scanning a locally directory, customize the location on disk where the server is started.'
    required: false
  directoryListing:
    description: 'Include an automatic directory index file when linking to a directory.'
    default: 'false'
    required: false
  retry:
    description: 'Automatically retry requests that return HTTP 429 responses and include a "retry-after" header.'
    default: 'false'
    required: false
  retryErrors:
    description: 'Automatically retry requests that return 5xx or network error responses.'
    default: 'false'
    required: false
  retryErrorsCount:
    description: 'The number of times to retry requests that return 5xx or network error responses. Defaults to 3.'
    default: '3'
    required: false
  retryErrorsJitter:
    description: 'The maximum jitter in milliseconds to apply to retry delays. Defaults to 2000.'
    default: '2000'
    required: false
  userAgent:
    description: 'Custom User-Agent header to use for requests.'
    required: false
  verbosity:
    description: 'Override the default verbosity for this command. Available options are "DEBUG", "INFO", "WARNING", "ERROR", and "NONE".  Defaults to "WARNING".'
    default: 'WARNING'
    required: false
  config:
    description: Path to a config file to use. Looks for `linkinator.config.json` by default. Options defined via the GitHub Action config will take precedence.
    required: false
  urlRewriteSearch:
    description: Pattern to search for in urls.  Must be used with `urlRewriteReplace`.
    required: false
  urlRewriteReplace:
    description: Expression used to replace search content.  Must be used with `urlRewriteSearch`.
    required: false
  allowInsecureCerts:
    description: Allow checking links with insecure certificates. Useful for local development with self-signed certificates.
    default: 'false'
    required: false
  requireHttps:
    description: Require all links to use HTTPS. Any HTTP links will be treated as broken.
    default: 'false'
    required: false
  cleanUrls:
    description: Enable support for clean URLs (extensionless paths). Allows validation of URLs without file extensions, useful for modern static hosting.
    default: 'false'
    required: false
  checkCss:
    description: Enable parsing and extraction of URLs from CSS files, style blocks, and inline styles.
    default: 'false'
    required: false
  checkFragments:
    description: Enable validation of fragment identifiers (anchor links) on HTML pages.
    default: 'false'
    required: false
  statusCodes:
    description: JSON object mapping HTTP status codes to actions (ok, warn, skip, error). Supports patterns like 4xx or 5xx. Example - {"404":"error","5xx":"warn"}
    required: false
  redirects:
    description: How to handle HTTP redirects. Options - "allow" (default), "warn", or "error".
    default: 'allow'
    required: false
outputs:
  results:
    description: 'The full results of the scan.'
runs:
  using: 'node24'
  main: 'dist/index.cjs'
