on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  test:
    needs: ncc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v1
  lint:
    needs: ncc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run lint
  ncc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
      - name: git push
        env:
          GITHUB_TOKEN: ${{ secrets.BECKWITH_ROBOT_TOKEN }}
        run: |
          git status
          git commit -a -m 'Follow up with a build'
          git push
